version: "3.2"

services:
  mongodb:
    image: mongo:5
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=chatgpt
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
        - "27017:27017"
    volumes:
      - /data/db
    networks:
      - chatgpt_local_db

  mongo_ui:
    depends_on:
      - mongodb
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://username:password@mongodb:27017
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - chatgpt_local_db



networks:
  chatgpt_local_db:
    driver: bridge